### ISSUE TITLE
Invalid managed/unmanaged type combination (Int64/UInt64 must be paired with I8 or U8)

### ISSUE THREAD

**Issue by MypowerHD** [IDNT/AppBasics-Virtualization-Libvirt#1]
Operating System: Debian GNU/Linux 10 (buster)
TargetFramework: netcoreapp3.1
Issue:
After building and deploy a test App to the linux host, i was able to get running your Demo code.
Then i add some code to get informations about the System like:
```C#
Console.WriteLine();
Console.WriteLine("[Node]");
var node = connection.Node;
Console.WriteLine($"Hostname: {node.Hostname}");
Console.WriteLine($"Memory(Free/All): {node.MemFreeBytes}/{node.MemoryBytes}");
Console.WriteLine($"CPU Sockets:{node.CpuSocketCount}");
Console.WriteLine($"CpuCores: {node.CpuCores}");
Console.WriteLine($"CPU Model: {node.CpuModelName}");
Console.WriteLine($"Threads: {node.CpuThreads}");
```

After deploying i run the Application.
On the Memory output throws following exception:
```
root@conmania-testing:/home/timo/pinvokeTest# ./Conversio.ProofOfConcept.PInvoke.Linux
[Node]
Hostname: conmania-testing.cookie.local
Unhandled exception. System.TypeLoadException: Cannot marshal field 'Memory' of type 'Libvirt.VirNodeInfo': Invalid managed/unmanaged type combination (Int64/UInt64 must be paired with I8 or U8).
   at System.StubHelpers.StubHelpers.FmtClassUpdateCLRInternal(Object obj, Byte* pNative)
   at Libvirt.NativeVirNode.GetInfo(IntPtr h, VirNodeInfo info)
   at Libvirt.LibvirtNode.GetInfo()
   at Conversio.ProofOfConcept.PInvoke.Linux.Program.Main(String[] args) in C:\Users\Timo\source\Workspaces\ConmaniaNext\ConversioIt.Conmania\Conversio.ProofOfConcept.PInvoke.Linux\Program.cs:line 18
Abgebrochen
```

Side info: may the Naming is wired because i was testing with this application some pinvokes with lxc. after that i clean the code and going to use libvirt-dotnet without renaming the project.

**Comment by mazocode** [comment]
Thank for reporting! We've just released some updates related to these parts of the code. Please let me know if this fixed the issue for you.

**Comment by mazocode** [comment]
Fixed with latest update.
