### ISSUE TITLE
How to create remote connection from Windows?

### ISSUE THREAD

**Issue by Alex-1357** [IDNT/AppBasics-Virtualization-Libvirt#3]
Hello, this is a question, maybe not an issue. LibVirtAuthentication is only an abstract class, and how to pass login/pass/rsakey for it?

    Using Connection = LibvirtConnection.Create.Connect("qemu+ssh://root@144.XX.XX.107/system?keyfile=id_rsa", _and_??_)
or 

     Using Connection = LibvirtConnection.Create.WithCredentials( _and_??_).Connect()

**Comment by Alex-1357** [comment]
Ups, sorry, I found signature.

             New OpenAuthPasswordAuth With {.Username = "root", .Password = "XXX"})

**Comment by Alex-1357** [comment]
And how to connect to remote host? I don't understand.

     Connect("qemu+ssh://root@144.XX.XX.107/")

get me this error:

    Libvirt.LibvirtConnectionException
      HResult=0x80131500
      Message=VIR_ERR_ERROR #VIR_ERR_INVALID_ARG invalid argument: transport methods unix, ssh and ext are not supported under Windows invalid argument: %s transport methods unix, ssh and ext are not supported under Windows
      Source=libvirt-dotnet
      StackTrace:
       at Libvirt.LibvirtConnection..ctor(IntPtr conn, LibvirtConfiguration configuration)
       at Libvirt.LibvirtConfiguration.Libvirt.IConfigurationBuilder.Connect(String uri, LibvirtAuthentication auth)
       at LibvirtNetCoreWrapper.Program.Main(String[] args) in E:\Projects\CryptoChestMax\LibvirtNetCoreWrapper\LibvirtNetCoreWrapper\Program.vb:line 7

and 

Connect("qemu://root@144.XX.XX.107/")

get me this error:

    Libvirt.LibvirtConnectionException
      HResult=0x80131500
      Message=VIR_ERR_ERROR #VIR_ERR_SYSTEM_ERROR Cannot read CA certificate '/usr/i686-w64-mingw32/sys-root/mingw/etc/pki/CA/cacert.pem': No such file or directory %s Cannot read CA certificate '/usr/i686-w64-mingw32/sys-root/mingw/etc/pki/CA/cacert.pem': No such file or directory
      Source=libvirt-dotnet
      StackTrace:
       at Libvirt.LibvirtConnection..ctor(IntPtr conn, LibvirtConfiguration configuration)
       at Libvirt.LibvirtConfiguration.Libvirt.IConfigurationBuilder.Connect(String uri, LibvirtAuthentication auth)
       at LibvirtNetCoreWrapper.Program.Main(String[] args) in E:\Projects\CryptoChestMax\LibvirtNetCoreWrapper\LibvirtNetCoreWrapper\Program.vb:line 7
