### ISSUE TITLE
Unable to load DLL 'libvirt-0.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)

### ISSUE THREAD

**Issue by Alex-1357** [IDNT/AppBasics-Virtualization-Libvirt#4]
I have successfully installed your library in Visual Studio 2019

     Install-Package libvirt-dotnet -Version 1.0.8

However, try to start show me this result

    System.TypeInitializationException
      HResult=0x80131534
      Message=The type initializer for 'Libvirt.LibvirtConnection' threw an exception.
      Source=libvirt-dotnet
      StackTrace:
       at Libvirt.LibvirtConnection.get_Create()
       at LibvirtNetCoreWrapper.Program.Main(String[] args) in E:\Projects\CryptoChestMax\LibvirtNetCoreWrapper\LibvirtNetCoreWrapper\Program.vb:line 7

    Inner Exception 1:
    DllNotFoundException: Unable to load DLL 'libvirt-0.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)

![Registry_12162021_014459](https://user-images.githubusercontent.com/86534217/146282285-60e8f63a-5638-4a9c-86e3-fce365adc84f.png)

Now I debug my application with VS2019 in Windows and than it will be deployed in Linux. I found this library in C:\Program Files (x86)\VirtViewer v9.0-256\bin (this is VNC/SPICE viewer from LibVirt). I found this lib and change project working lib to C:\Program Files (x86)\VirtViewer v9.0-256\bin - but no result, error message not changed.

**Comment by Alex-1357** [comment]
Ups, and finally changing working directory, changing version of SPICE viewer and change VS2019 image helped me. I receive new error:

    Libvirt.LibvirtConnectionException
      HResult=0x80131500
      Message=VIR_ERR_ERROR #VIR_ERR_SYSTEM_ERROR Cannot read CA certificate '/usr/i686-w64-mingw32/sys-root/mingw/etc/pki/CA/cacert.pem': No such file or directory %s Cannot read CA certificate '/usr/i686-w64-mingw32/sys-root/mingw/etc/pki/CA/cacert.pem': No such file or directory
     Source=libvirt-dotnet
     StackTrace:
      at Libvirt.LibvirtConnection..ctor(IntPtr conn, LibvirtConfiguration configuration)
      at Libvirt.LibvirtConfiguration.Libvirt.IConfigurationBuilder.Connect(String uri, LibvirtAuthentication auth)
      at LibvirtNetCoreWrapper.Program.Main(String[] args) in E:\Projects\CryptoChestMax\LibvirtNetCoreWrapper\LibvirtNetCoreWrapper\Program.vb:line
